openscd/open-scd

src/wizard-textfield.ts
=> fix(wizard-textfield): reset custom validity

src/editors/substation/voltage-level-editor.ts, src/foundation.ts
=> Fix remove voltage level

src/editors/substation/bay-editor.ts, src/editors/substation/conducting-equipment-editor.ts, src/editors/substation/substation-editor.ts, src/editors/substation/voltage-level-editor.ts
=> fix(substaiton/editors): delete tailingIcon from desc and name textfield

src/editors/substation/bay-editor.ts, src/editors/substation/conducting-equipment-editor.ts, src/editors/substation/substation-editor.ts, src/editors/substation/voltage-level-editor.ts
=> fix(substation/editors): desc textfield default empty string

src/editors/substation/conducting-equipment-editor.ts
=> fix(conducting-equipment-editor): center name the conducting equipment

__snapshots__/open-scd.md, src/Editing.ts, src/Logging.ts, src/foundation.ts, test/unit/Editing.test.ts, test/unit/foundation.test.ts, test/unit/mock-actions.ts
=> Add complex actions

src/Logging.ts, src/themes.ts
=> fix(themes): add list-item text colors

src/Importing.ts, src/Validating.ts, src/Waiting.ts, src/foundation.ts, src/open-scd.ts, test/integration/open-scd.test.ts, test/unit/Waiting.test.ts, test/unit/foundation.test.ts
=> fix(logging): do not log results of long running processes twice

src/editors/communication/foundation.ts, src/editors/substation/foundation.ts
=> fix(editors/styling): add abbrevaition style

__snapshots__/conducting-equipment-editor.md, __snapshots__/connectedap-editor.md, src/editors/communication/connectedap-editor.ts, src/editors/substation/conducting-equipment-editor.ts, test/integration/editors/communication/connectedap-editor-wizarding-editing.test.ts, test/integration/editors/communication/connectedap-editor-wizarding.test.ts, test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts, test/integration/editors/substation/conducting-equipment-editor-wizarding.test.ts
=> fix(editors/substation/conducting-equipment): overlapping icon buttons

test/data.ts, test/integration/editors/communication/Communication.test.ts, test/integration/editors/substation/Substation.test.ts, test/integration/editors/templates/Templates.test.ts, test/unit/editors/communication/ConnectedAPEditor.test.ts, test/unit/editors/communication/SubNetwork.test.ts, test/unit/editors/communication/conductingap-editor.test.ts, test/unit/editors/communication/subnetwork-editor.test.ts
=> test(editors): add missing integration tests

src/editors/substation/substation-editor.ts
=> fix(editors/substation): remove horizontal scroll bar on overflow

src/open-scd.ts
This finally closes #7 , one of our most long-standing issues 🥳
=> fix: allow re-opening the same file again

__snapshots__/open-scd.md, src/Logging.ts, test/integration/open-scd.test.ts, test/unit/Logging.test.ts
Closes #184 .
I did not manage to regenerate test snapshots and would appreciate help with this.
=> feat(logging): show snackbars on info and warning

__snapshots__/filtered-list.md, src/filtered-list.ts, test/unit/filtered-list.test.ts
=> feat(filtered-list): add check all to filtered-list

ROADMAP.md
=> doc(roadmap): initial readme

__snapshots__/subnetwork-editor.md, src/editors/Communication.ts, src/editors/communication/connectedap-editor.ts, src/editors/communication/foundation.ts, src/editors/communication/subnetwork-editor.ts, test/unit/editors/communication/ConnectedAPEditor.test.ts, test/unit/editors/communication/SubNetwork.test.ts
=> feat(communication-editor): show all connected ap within ied

src/foundation.ts, src/triggered/SubscriberInfo.ts, test/testfiles/subscriberinfo2003.scd, test/testfiles/subscriberinfo2007.scd, test/unit/editors/subscriberinfo.test.ts
=> feat(subscriberinfo): add subscriber info to sampledvaluecontrol

src/editors/communication/connectedap-editor.ts, src/editors/substation/guess-wizard.ts, src/editors/substation/lnodewizard.ts, src/filtered-list.ts, src/foundation.ts, src/triggered/CommunicationMapping.ts, src/wizard-dialog.ts, test/integration/editors/substation/bay-editor-wizarding-editing.test.ts, test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts, test/integration/editors/substation/substation-editor-wizarding-editing.test.ts, test/integration/editors/substation/voltage-level-editor-wizarding-editing.test.ts, test/unit/filtered-list.test.ts
=> Add lists to wizard actor

__snapshots__/Templates Plugin.md, src/editors/Templates.ts, src/translations/de.ts, src/translations/en.ts, test/integration/editors/templates/datype-wizarding.test.ts, test/integration/editors/templates/dotype-wizarding.test.ts
=> feat(editors/templates): add read-only LNodeType to 

src/editors/templates/dotype-wizards.ts, src/translations/de.ts, src/translations/en.ts
=> C dinkel patch 1

__snapshots__/DAType wizards.md, __snapshots__/DOType wizards.md, __snapshots__/LNodeType wizards.md, __snapshots__/Templates Plugin.md, public/xml/templates.scd, src/editors/Templates.ts, src/editors/templates/datype-wizards.ts, src/editors/templates/dotype-wizards.ts, src/editors/templates/foundation.ts, src/editors/templates/lnodetype-wizard.ts, src/foundation.ts, src/translations/de.ts, src/translations/en.ts, test/integration/editors/templates/lnodetype-wizard.test.ts, test/integration/open-scd.test.ts
=> feat(editors/templates/lnodetype-wizards): add basic lnodetype manipulation capabilities

src/editors/Templates.ts
=> fix(templates): adjust width setting to better fit to small portable devices

__snapshots__/open-scd.md, public/js/plugins.js, src/Hosting.ts, src/Plugging.ts, src/Setting.ts, src/menu/CommunicationMapping.ts, src/menu/ImportIEDs.ts, src/menu/Merge.ts, src/menu/NewProject.ts, src/menu/OpenProject.ts, src/menu/SaveProject.ts, src/menu/SubscriberInfo.ts, src/menu/UpdateSubstation.ts, src/translations/de.ts, src/translations/en.ts, src/validators/ValidateSchema.ts, src/wizards.ts, test/integration/editors/triggered/CommunicationMappingPlugin.test.ts, test/integration/editors/triggered/ImportIedsPlugin.test.ts, test/integration/loaders/NewProject.test.ts, test/unit/Plugging.test.ts, test/unit/editors/communicationmapping.test.ts, test/unit/editors/subscriberinfo.test.ts, test/unit/editors/updatesubstation.test.ts
We wanted to add the about-box as another plugin and realized that the plugin API might need another refactor.
@dlabordus you might want to review as well.
=> Refactor plugins

src/editors/substation/lnodewizard.ts, src/foundation.ts, test/integration/editors/substation/lnodewizard.test.ts, test/unit/foundation.test.ts
=> fix(substation/lnodewizard): oldNodes are only child nodes of an element

__snapshots__/open-scd.md, src/Logging.ts, src/foundation.ts, src/icons.ts, src/menu/NewProject.ts, src/menu/OpenProject.ts, src/open-scd.ts, test/unit/Logging.test.ts
=> refactor(logging): add reset kind log event

__snapshots__/finder-pane.md, public/md/Connect-Report-Control-Blocks-with-ClientLN.md, public/md/DataTypeTemplate-editor.md, public/md/Guess-substation-structure.md, public/md/Home.md, public/md/How-to-install-OpenSCD-offline.md, public/md/Importing-IEDs.md, public/md/Manage-save-project.md, public/md/Merge-functionality.md, public/md/Update-GOOSE-subscriber-info-in-SCL.md, public/md/_Sidebar.md, src/finder-pane.ts, src/foundation.ts, src/open-scd.ts, test/unit/finder-pane.test.ts
=> refactor: add finder-pane for tree nagivation

src/Plugging.ts
=> fix(plugging): fix plugin auto-update

__snapshots__/DOType wizards.md, public/xml/templates.scd
=> fix(templates): add missing SwTyp and fix wrong cdc

src/editors/communication/connectedap-editor.ts, src/editors/communication/subnetwork-editor.ts, src/editors/substation/bay-editor.ts, src/editors/substation/conducting-equipment-editor.ts, src/editors/substation/foundation.ts, src/editors/substation/substation-editor.ts, src/editors/substation/voltage-level-editor.ts, src/editors/templates/datype-wizards.ts, src/editors/templates/dotype-wizards.ts, src/editors/templates/enumtype-wizard.ts, src/editors/templates/lnodetype-wizard.ts, src/foundation.ts, src/menu/CommunicationMapping.ts, src/wizard-dialog.ts, src/wizards.ts, src/wizards/voltagelevel.ts, test/unit/Editing.test.ts
=> refactor(foundation): change reference type to Node

__snapshots__/LNodeType wizards.md, src/editors/templates/lnodetype-wizard.ts, test/testfiles/updatesubstation-ours.scd, test/unit/editors/communication/SubNetwork.test.ts
=> Test errors in firefox but not in chrome

src/translations/de.ts, src/translations/en.ts, src/validators/ValidateSchema.ts, src/validators/ValidateTemplates.ts, test/integration/editors/templates/lnodetype-wizard.test.ts, test/integration/validators/ValidateTemplates.test.ts, test/testfiles/validators/datatypetemplateerrors.scd, test/unit/validators/ValidateTemplates.test.ts
=> fix(validatetemplates): don't require "Oper" if ctlModel=status-only

src/filtered-list.ts, test/unit/filtered-list.test.ts
=> feat(filtered-list): select only visible items on checkAll

src/editors/communication/subnetwork-editor.ts, src/editors/templates/dotype-wizards.ts, src/editors/templates/enumtype-wizard.ts, src/editors/templates/foundation.ts, src/editors/templates/lnodetype-wizard.ts, src/foundation.ts, src/wizards/bay.ts, src/wizards/bda.ts, src/wizards/conductingequipment.ts, src/wizards/da.ts, src/wizards/dataset.ts, src/wizards/foundation/actions.ts, src/wizards/gsecontrol.ts, src/wizards/substation.ts, src/wizards/voltagelevel.ts, src/zeroline/bay-editor.ts, src/zeroline/foundation.ts, src/zeroline/substation-editor.ts, src/zeroline/voltage-level-editor.ts, test/unit/foundation.test.ts, test/unit/zeroline/BayEditor.test.ts, test/unit/zeroline/ConductingEquipmentEditor.test.ts, test/unit/zeroline/SubstationEditor.test.ts
=> refactor(foundation): add cloneElement function

src/zeroline/ied-editor.ts
=> fix(ied-editor): add tooltip with full IED name

package.json
=> fix(package.json): license change

__snapshots__/open-scd.md, src/Logging.ts, src/foundation.ts, src/icons.ts, test/testfiles/history.scd, test/unit/Logging.test.ts
=> feat(Logging): show Hitem from SCL

src/wizards/conductingequipment.ts
Change the word Genarator to address issue #318
=> Spell correction

src/filtered-list.ts
=> style(filted-list): fix styling add doc

src/wizards/reportcontrol.ts, src/zeroline-pane.ts, test/integration/zeroline-pane.test.ts, test/unit/__snapshots__/zeroline-pane.test.snap.js, test/unit/wizards/__snapshots__/reportcontrol.test.snap.js, test/unit/wizards/reportcontrol.test.ts
=> feat(wizards/reportcontrol): add select wizard

src/foundation.ts, test/foundation.ts, test/integration/editors/templates/__snapshots__/lnodetype-wizard.test.snap.js, test/integration/editors/templates/lnodetype-wizard.test.ts, test/unit/editors/templates/lnodetype-wizard.test.ts
=> fix(editors/template/lnodetype): fix incorrect pattern for lnClass

src/translations/de.ts, src/translations/en.ts, src/wizards/sampledvaluecontrol.ts, src/zeroline-pane.ts, src/zeroline/ied-editor.ts, test/integration/zeroline-pane.test.ts, test/testfiles/wizards/sampledvaluecontrol.scd, test/unit/__snapshots__/zeroline-pane.test.snap.js, test/unit/wizards/__snapshots__/sampledvaluecontrol.test.snap.js, test/unit/wizards/sampledvaluecontrol.test.ts, test/unit/zeroline/__snapshots__/ied-editor.test.snap.js, test/unit/zeroline/ied-editor.test.ts
With `SampledValueControl ` element, I thought to make smaller steps immediately usable by the user. Showing `SampledValueControl` element is already interesting enough :)
Closes #426
=> feat(zeroline): show SampledValueControl for IED and whole project

src/wizards/reportcontrol.ts, test/integration/wizards/reportcontrol-wizarding-editing.test.ts, test/unit/wizards/__snapshots__/reportcontrol.test.snap.js, test/unit/wizards/reportcontrol.test.ts
=> feat(wizards/reportcontrol): add remove option to edit wizard

src/editors/ied/ied-container.ts, src/translations/de.ts, src/translations/en.ts, src/wizards/foundation/references.ts, src/wizards/ied.ts, src/wizards/wizard-library.ts, src/zeroline/ied-editor.ts, test/testfiles/wizards/ied.scd, test/unit/editors/ied/__snapshots__/ied-container.test.snap.js, test/unit/wizards/__snapshots__/ied.test.snap.js, test/unit/wizards/foundation.ts, test/unit/wizards/foundation/references.test.ts, test/unit/wizards/ied.test.ts, test/unit/zeroline/__snapshots__/ied-editor.test.snap.js
Also all SCL elements referencing that IED Name are updated.
=> feat(wizards/reportcontrol): added new IED wizard to update name/description

src/action-pane.ts
=> style(action-pane): clip heading label

src/open-scd.ts
Make sure to center the landing icons on the page
=> style: center landing icons

src/menu/Help.ts
=> fix(menu/Help): incorrect import of markup parser

src/Plugging.ts, test/integration/__snapshots__/open-scd.test.snap.js
Based on the user feedback in #533 I have adapted the UI slightly. @Sander3003 what do you think about this?
Close #533
=> refactor(Plugins): improve extentions UI

src/wizards/sampledvaluecontrol.ts, test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts, test/unit/wizards/__snapshots__/sampledvaluecontrol.test.snap.js, test/unit/wizards/sampledvaluecontrol.test.ts
=> feat(wizard/sampledvaluecontrol): allow removing incl. referenced elements

src/Editing.ts, src/editors/templates/foundation.ts, src/foundation.ts, src/translations/de.ts, src/translations/en.ts, test/unit/Editing.test.ts, test/unit/editors/subscriberinfo.test.ts, test/unit/wizards/address.test.ts, test/unit/wizards/bda.test.ts, test/unit/wizards/connectedap.test.ts, test/unit/wizards/da.test.ts, test/unit/wizards/gse.test.ts, test/unit/wizards/smv.test.ts, test/unit/wizards/subnetwork.test.ts
..this is the second of the two that completes the refactor of the existing Editor Actions. After that is merged I will add a new editor action `Update` to the foundation
=> refactor(Editing): allow create and delete Node s

public/xml/templates.scd, src/editors/templates/dotype-wizards.ts, src/editors/templates/lnodetype-wizard.ts, test/integration/editors/templates/lnodetype-wizard.test.ts
Fixes some minor issues related to the `Template` editor type plugin
=> Minor fixes lnodetype

src/editors/ied/da-container.ts, src/editors/ied/ln-container.ts, test/unit/editors/ied/__snapshots__/da-container.test.snap.js, test/unit/editors/ied/da-container.test.ts
=> feat(plugins/IED): Added Functional Constraint value to DA Container.

src/editors/singlelinediagram/sld-drawing.ts, src/editors/substation/bay-editor.ts, src/editors/substation/conducting-equipment-editor.ts, src/editors/substation/foundation.ts, src/editors/substation/ied-editor.ts, src/editors/substation/substation-editor.ts, src/editors/substation/voltage-level-editor.ts, src/zeroline-pane.ts, test/integration/zeroline/bay-editor-wizarding-editing.test.ts, test/integration/zeroline/bay-editor-wizarding.test.ts, test/integration/zeroline/conducting-equipment-editor-wizarding-editing.test.ts, test/integration/zeroline/conducting-equipment-editor-wizarding.test.ts, test/integration/zeroline/ied-editor-wizarding-integration.test.ts, test/integration/zeroline/substation-editor-wizarding-editing.test.ts, test/integration/zeroline/substation-editor-wizarding.test.ts, test/integration/zeroline/voltage-level-editor-wizarding-editing.test.ts, test/integration/zeroline/voltage-level-editor-wizarding.test.ts, test/unit/action-pane.test.ts, test/unit/wizards/clientln.test.ts, test/unit/zeroline-pane.test.ts, test/unit/zeroline/bay-editor.test.ts, test/unit/zeroline/conducting-equipment-editor.test.ts, test/unit/zeroline/ied-editor.test.ts, test/unit/zeroline/substation-editor.test.ts, test/unit/zeroline/voltage-level-editor.test.ts
The first of couple refactoring steps with substation type editors
=> refactor: move editors back to substation folder

src/wizard-checkbox.ts
Little change, but a lot more readable. Thanks @danyill for the hint :)
close #555
=> style(wizard-checkbox): highlight human readable information

src/action-pane.ts
=> fix(action-pane): adjust css rules for icon slot

src/translations/de.ts, src/translations/en.ts, src/wizards/gsecontrol.ts, src/wizards/reportcontrol.ts, src/wizards/sampledvaluecontrol.ts, test/unit/wizards/gsecontrol.test.ts, test/unit/wizards/reportcontrol.test.ts, test/unit/wizards/sampledvaluecontrol.test.ts
=> refactor(wizards/reportcontrol): use report update action

test/unit/editors/ied/__snapshots__/da-container.test.snap.js, test/unit/editors/ied/__snapshots__/do-container.test.snap.js
=> fix(plugin/IED) da-container/do-container snapshot files keep refreshing when building OpenSCD

src/editors/sampledvalues/subscriber-ied-list.ts, test/integration/editors/sampledvalues/SampledValues.test.ts, test/integration/editors/sampledvalues/__snapshots__/SampledValues.test.snap.js, test/testfiles/valid2007B4ForSampledValues.scd
=> feat(plugins/SampledValues): Small bug fix + Added Integration tests

src/editors/Communication.ts
=> refactor(plugins/Communication): Add styling for Communication section

src/wizards/conductingequipment.ts
Closes #610
A bit of lint in this from prettier. Hope that's OK.
=> refactor(wizards/conductingequipment): Correct earth switch symbol application to ConductingEquipment

src/editors/templates/datype-wizards.ts, test/integration/editors/templates/__snapshots__/datype-wizarding.test.snap.js, test/integration/editors/templates/datype-wizarding.test.ts, test/integration/wizards/bda-wizarding-editing.test.ts
Proceeding to remove buttons from wizard-dialog content
=> refactor(editor/template/datype): use menu actions

src/wizards/gsecontrol.ts, test/integration/wizards/gsecontrolwizarding-editing.test.ts, test/integration/wizards/reportcontrol-wizarding-editing.test.ts, test/unit/wizards/__snapshots__/gsecontrol.test.snap.js, test/unit/wizards/gsecontrol.test.ts
Proceeding with removing mwc-button s from wizard-dialog content.
=> refactor(wizards/gsecontrol): remove button from wizard content

src/wizards/bda.ts, src/wizards/da.ts, test/integration/wizards/__snapshots__/bda-wizarding-editing.test.snap.js, test/integration/wizards/__snapshots__/da-wizarding-editing.test.snap.js, test/integration/wizards/bda-wizarding-editing.test.ts, test/integration/wizards/da-wizarding-editing.test.ts
Proceeding to remove `mwc-button` from `wizard-dialog`s content. One to come
=> Refactor da bda wizards use menu actions

src/wizards/subnetwork.ts, test/unit/wizards/__snapshots__/subnetwork.test.snap.js
=> fix(wizards/subnetwork): incorrect title for create wizard

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
We were speaking about this in some meetings already, and I had time on my hands now :). The template for bugs were good enough for me. I did adopt the feature request template slightly to our needs. !This is a suggestion! Please see it a such and comment :).
=> chore: add issue templates for bug and feature request

src/editors/ied/da-container.ts, src/editors/ied/do-container.ts, src/editors/ied/foundation.ts, test/unit/editors/ied/do-container.test.ts, test/unit/editors/ied/foundation.test.ts
=> bug(iededitor): Fixed processing SDI Elements with structs in DA/DO Containers.

src/editors/ied/foundation/foundation.ts, src/wizards/dai.ts, test/testfiles/valid2007B4ForDAIValidation.scd, test/unit/editors/ied/foundation/__snapshots__/foundation.test.snap.js, test/unit/editors/ied/foundation/foundation.test.ts
=> feat(iededitor): Added implementation to change enum values in IED Editor.

src/editors/substation/sub-function-editor.ts, src/wizards/subfunction.ts, src/wizards/wizard-library.ts, test/integration/editors/substation/sub-function-editor.test.ts, test/testfiles/zeroline/functions.scd, test/unit/editors/substation/__snapshots__/sub-function-editor.test.snap.js, test/unit/wizards/__snapshots__/subfunction.test.snap.js, test/unit/wizards/subfunction.test.ts
One of four PRs covering #332 integrating edit wizard for `SubFunction`
=> feat(wizards/subfunction): add edit wizard

src/editors/substation/eq-function-editor.ts, src/wizards/eqfunction.ts, src/wizards/wizard-library.ts, test/integration/editors/substation/eq-function-wizarding-editing.test.ts, test/testfiles/zeroline/functions.scd, test/unit/editors/substation/__snapshots__/eq-function-editor.test.snap.js, test/unit/wizards/__snapshots__/eqfunction.test.snap.js, test/unit/wizards/eqfunction.test.ts
One of four PRs covering #332 adding edit wizard for `EqFunction`
=> feat(wizards/eqfunction): add edit wizard

src/editors/substation/eq-sub-function-editor.ts, src/wizards/eqsubfunction.ts, src/wizards/wizard-library.ts, test/integration/editors/substation/eq-sub-function-editor-wizarding-editing.test.ts, test/testfiles/zeroline/functions.scd, test/unit/editors/substation/__snapshots__/eq-sub-function-editor.test.snap.js, test/unit/wizards/__snapshots__/eqsubfunction.test.snap.js, test/unit/wizards/eqsubfunction.test.ts
One of four PRs covering #332 adding edit wizard for `EqSubFunction` type editor
=> feat(wizards/eqsubfunction): add edit wizard

src/editors/protocol104/network-container.ts, src/editors/protocol104/wizards/subnetwork.ts, test/unit/editors/protocol104/wizards/__snapshots__/subnetwork.test.snap.js, test/unit/editors/protocol104/wizards/subnetwork.test.ts
=> feat(editors/104): As an engineer I want to create a new 104 subnet

src/editors/substation/bay-editor.ts, src/editors/substation/conducting-equipment-editor.ts, src/editors/substation/l-node-editor.ts, src/editors/substation/powertransformer-editor.ts, src/editors/substation/substation-editor.ts, src/editors/substation/voltage-level-editor.ts, src/translations/de.ts, src/translations/en.ts, src/wizards/lnode.ts, src/wizards/wizard-library.ts, test/integration/editors/substation/l-node-editor-wizarding-editing.test.ts, test/unit/editors/substation/__snapshots__/l-node-editor.test.snap.js, test/unit/wizards/__snapshots__/lnode.test.snap.js, test/unit/wizards/lnode.test.ts
=> feat(wizards/lnode): add edit wizard

index.html
=> feat(general): prevent losing data on user navigation

src/editors/protocol104/wizards/doi.ts, test/unit/editors/protocol104/wizards/__snapshots__/doi.test.snap.js, test/unit/editors/protocol104/wizards/doi.test.ts
=> feat(104/ShowDOIWizard): Show detailed info about known/found TIs

src/editors/protocol104/wizards/address.ts
=> fix(104/address): Input fields are reset when using multiple time

src/editors/Communication.ts, src/editors/communication/subnetwork-editor.ts, src/foundation.ts, src/wizards/foundation/p-types.ts, test/integration/editors/communication/__snapshots__/subnetwork-editor-wizarding-editing.test.snap.js, test/integration/editors/communication/subnetwork-editor-wizarding-editing.test.ts, test/integration/editors/communication/subnetwork-editor-wizarding.test.ts, test/unit/editors/communication/__snapshots__/subnetwork-editor.test.snap.js, test/unit/editors/communication/subnetwork-editor.test.ts
Closes #818 .
This is a draft because it still requires regression tests, but the fix itself is ready to review.
=> fix(communication): display changes to ConnectedAPs in SubNetworks

src/editors/protocol104/foundation/foundation.ts, src/editors/protocol104/wizards/selectDo.ts
Small changes to the Element Queries and one fix that LN can also be directly below a AccessPoint.
=> fix(editor/104): Small improvements and fix.

src/editors/substation/zeroline-pane.ts
Closes #898.
If I learnt anything from the reactive updates discussion, then perhaps this is an acceptable fix :wink: 
It does seem to work, which makes me happy.
=> fix(editor/substation): Updated IED name is shown in IED container

src/editors/publisher/gse-control-editor.ts, src/editors/publisher/gse-control-element-editor.ts, test/unit/editors/publisher/__snapshots__/gse-control-editor.test.snap.js, test/unit/editors/publisher/__snapshots__/gse-control-element-editor.test.snap.js, test/unit/editors/publisher/gse-control-element-editor.test.ts
Adding read only GSEControl element editor with same UI as for Report. Would love to hear your review.
=> feat(editors/publisher): add read only gse-control-element-editor

.github/ISSUE_TEMPLATE/feature_request.md
We have identified that a minimum viable test file is a very good starting point when working on a feature. It is also a good way to check the feature afterward. I therefore propose to make it a bit more visible and add an optional test file request into the feature issue template.
=> chore(ISSUE_TEMPLATE/feature): add optional test file request 

src/wizards/gsecontrol.ts, test/unit/wizards/gsecontrol.test.ts
=> fix(wizard/gsecontrol): Fix schema validation error after creating GSE Control (MinTime)

public/md/Extensions.md, public/md/Home.md, public/md/_Sidebar.md
Hopefully, this is about right. I would be pleased to take a review.
=> Document extensions and scroll behaviour on wiki, closes #557

src/menu/ImportIEDs.ts, test/integration/editors/triggered/ImportIedsPlugin.test.ts, test/testfiles/importieds/emptyproject.scd
Closes #1011 
See description of the bug in the issue.
=> fix(menu/importieds): allow import to new projects

src/editors/subscription/later-binding/fcda-later-binding-list.ts
Closes #1017
Happy to receive a review.
=> fix(editors/subscriber-later-binding): Add GOOSE icon to later binding editor

src/editors/subscription/fcda-binding-list.ts, src/editors/subscription/foundation.ts, test/integration/editors/GooseSubscriberDataBinding.test.ts, test/integration/editors/GooseSubscriberLaterBinding.test.ts, test/integration/editors/SMVSubscriberDataBinding.test.ts, test/integration/editors/SMVSubscriberLaterBinding.test.ts, test/integration/editors/test-support.ts, test/unit/editors/subscription/__snapshots__/fcda-binding-list.test.snap.js
=> bug(editor/subscriber): Filtering on FCDA Value as displayed made possible

test/unit/Logging.test.ts
See [comment](https://github.com/openscd/open-scd/pull/1034#issuecomment-1299623520).
This should fix the broken tests which should not be broken.
=> fix(Logging): proper event usage

ROADMAP.md
Signed-off-by: Sander Jansen <sander.jansen@alliander.com>
=> Improvement suggestions

ROADMAP.md
Jakob Birnbaumer and Fred Steinhauser from OMICRON discussed updating the roadmap with @Sander3003, @JakobVogelsang, and me. This is our initial suggestion for an unsorted list of general feature wishes.
Let's discuss the points raised here until we have collected all important points before we merge the change back to main.
=> doc: update roadmap with current feature ideas

src/menu/ImportIEDs.ts, test/integration/editors/triggered/ImportIedsPlugin.test.ts, test/testfiles/importieds/template.icd
=> fix(menu/importieds) Import IEDs with Communication section if IED named TEMPLATE

src/editors/substation/general-equipment-editor.ts, src/wizards/generalEquipment.ts, src/wizards/wizard-library.ts, test/integration/editors/substation/general-equipment-editor-wizard-editing.test.ts, test/testfiles/editors/substation/generalequipment.scd, test/unit/editors/substation/__snapshots__/general-equipment-editor.test.snap.js, test/unit/editors/substation/__snapshots__/substation-editor.test.snap.js, test/unit/wizards/__snapshots__/generalequipment.test.snap.js, test/unit/wizards/generalequipment.test.ts
All the changes previously committed to 976_add_general_equipment_edit_wizard are now included in one single commit in this new branch.
Closes #976
=> feat(substation/general-equipment-editor): edit wizard

src/menu/ImportIEDs.ts, test/integration/editors/triggered/ImportIedsPlugin.test.ts, test/testfiles/importieds/template.icd
This PR is primarily fixing #1052. However, I invested also so time to remove the dependency from wizard-dialog. 
@danyill would you be so kind and test it with some files. I would not want to break, repair it again. :)
=> fix(ieds-import): multiple IEDs import

README.md
Copy from the open-scd-core words.
=> (docs/readme): Add chat channel info

src/editors/communication/gse-editor.ts, src/editors/communication/smv-editor.ts, test/integration/editors/communication/gse-editor-wizarding-editing.test.ts, test/integration/editors/communication/smv-editor-wizarding-editing.test.ts, test/unit/editors/communication/__snapshots__/gse-editor.test.snap.js, test/unit/editors/communication/__snapshots__/smv-editor.test.snap.js, test/unit/editors/communication/gse-editor.test.ts, test/unit/editors/communication/smv-editor.test.ts
Just a little missing thing which we thought would be nice.
=> feat(editors/Communication) Allow editing of GSE/SMV in the Communication editor. Closes #1126

src/menu/ImportIEDs.ts, test/integration/editors/triggered/ImportIedsPlugin.test.ts
=> fix(menu/ImportIEDs) correct TEMPLATE name for illegal characters

src/editors/substation/transformer-winding-editor.ts, test/integration/editors/substation/transformer-winding-editor-wizard-editing.test.ts, test/unit/editors/substation/__snapshots__/transformer-winding-editor.test.snap.js
Changed in transformer-winding-editor-wizard-edititing.test.ts the argument of querySelector to handle the element with name some.
=> feat(editors/substation/transformerwinding): add remove button 

src/editors/ied/da-container.ts, src/editors/ied/da-wizard.ts, src/editors/ied/foundation.ts, src/wizards/dai.ts, src/wizards/foundation/dai-field-type.ts, test/testfiles/editors/iedEditorWithIEDs.scd, test/testfiles/wizards/ied.scd, test/unit/editors/ied/__snapshots__/da-container.test.snap.js, test/unit/editors/ied/da-container.test.ts, test/unit/editors/ied/foundation.test.ts, test/unit/wizards/__snapshots__/dai.test.snap.js, test/unit/wizards/dai.test.ts
=> feat(editors/ied): show all instantiated setting group values

src/editors/substation/tapchanger-editor.ts, test/integration/editors/substation/tapchanger-editor-wizard-editing.test.ts, test/unit/editors/substation/__snapshots__/tapchanger-editor.test.snap.js
=> 974 add button tapchanger

src/translations/de.ts, src/translations/en.ts
=> fix: added translation key for phase

public/js/plugins.js, test/integration/__snapshots__/open-scd.test.snap.js, test/unit/Plugging.test.ts
=> fix: enable IED editor plugin by default

public/js/plugins.js, test/integration/__snapshots__/open-scd.test.snap.js
=> fix: enable compare plugin by default

public/js/plugins.js, test/integration/__snapshots__/open-scd.test.snap.js, test/unit/Plugging.test.ts, test/unit/editors/subscription/fcda-binding-list.test.ts
=> fix: only later binding  subscribers by default

docs/adr/0001-record-architecture-decisions.md, docs/decisions/0001-record-architecture-decisions.md
Rendered version: [1. Record Architecture Decision](https://github.com/openscd/open-scd/blob/caabedfdee3c48820a8e3b4160c4c5b21a4d7b59/docs/adr/0001-record-architecture-decisions.md)
=> Initalize ADR for the repository

packages/open-scd/src/menu/UpdateSubstation.ts
=> Chore: Moved mergeSubstation function outside the UpdateSubstation plugin, so it can be reused

packages/open-scd/src/foundation.ts
fixes #1339 
chore: Added optional Element to IssueDetail
=> Added optional Element to IssueDetail

packages/open-scd/src/Historing.ts, packages/open-scd/src/Hosting.ts, packages/open-scd/src/Logging.ts, packages/open-scd/src/Plugging.ts, packages/open-scd/src/open-scd.ts, packages/open-scd/src/translations/de.ts, packages/open-scd/src/translations/en.ts, packages/open-scd/test/integration/Setting.test.ts, packages/open-scd/test/integration/__snapshots__/open-scd.test.snap.js, packages/open-scd/test/integration/editors/GooseSubscriberDataBinding.test.ts, packages/open-scd/test/integration/editors/GooseSubscriberLaterBinding.test.ts, packages/open-scd/test/integration/editors/GooseSubscriberMessageBinding.test.ts, packages/open-scd/test/integration/editors/SMVSubscriberDataBinding.test.ts, packages/open-scd/test/integration/editors/SMVSubscriberLaterBinding.test.ts, packages/open-scd/test/integration/editors/SMVSubscriberMessageBinding.test.ts, packages/open-scd/test/integration/editors/__snapshots__/GooseSubscriberMessageBinding.test.snap.js, packages/open-scd/test/integration/editors/__snapshots__/SMVSubscriberMessageBinding.test.snap.js, packages/open-scd/test/integration/editors/triggered/ImportIedsPlugin.test.ts, packages/open-scd/test/integration/open-scd.test.ts, packages/open-scd/test/integration/validators/ValidateSchema.test.ts, packages/open-scd/test/mock-editor-logger.ts, packages/open-scd/test/mock-setter-logger.ts, packages/open-scd/test/unit/Historing.test.ts, packages/open-scd/test/unit/Logging.test.ts, packages/open-scd/test/unit/mock-logger.ts, packages/open-scd/test/unit/mock-plugger.ts
=> Split logging

packages/open-scd/src/editors/protocol104/foundation/cdc.ts, packages/open-scd/test/unit/editors/protocol104/wizards/__snapshots__/doi.test.snap.js, packages/open-scd/test/unit/editors/protocol104/wizards/doi.test.ts
=> feat: added acd as a supported cdc type

packages/open-scd/src/editors/protocol104/foundation/signalNames.ts, packages/open-scd/src/editors/protocol104/wizards/address.ts, packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts, packages/open-scd/src/translations/de.ts, packages/open-scd/src/translations/en.ts, packages/open-scd/test/unit/editors/protocol104/wizards/__snapshots__/createAddresses.test.snap.js, packages/open-scd/test/unit/editors/protocol104/wizards/createAddresses.test.ts
=> feat(104): added descriptions to ti numbers

packages/open-scd/src/editors/protocol104/foundation/cdc.ts, packages/open-scd/test/unit/editors/protocol104/wizards/selectDo.test.ts
=> feat(104): added ens as a supported cdc type

packages/open-scd/public/xml/Disclaimer.md
Add disclaimer to prevent confusion about the license of the nsd files.
=> docs: added Disclaimer.md to prevent confusion

packages/open-scd/src/editors/templates/dotype-wizards.ts, packages/open-scd/test/integration/editors/templates/__snapshots__/dotype-wizarding.test.snap.js
=> fix: fixed dotype-wizarding test for correct translation

packages/open-scd/src/icons/icons.ts, packages/plugins/test/unit/editors/singlelinediagram/__snapshots__/sld-drawing.test.snap.js
=> fix: use materialized icons for primary apparatus

packages/addons/package.json, packages/components/package.json, packages/distribution/package.json, packages/wizards/package.json
=> chore: commenting out scripts from shell projects

package-lock.json, packages/open-scd/src/open-scd.ts, packages/open-scd/test/integration/__snapshots__/open-scd.test.snap.js, packages/open-scd/test/integration/open-scd.test.ts
Also includes:
- test: fixing snapshot tests for passing down plugins as props
- ci: fixing invalid characters in package-lock.json (in order to fix dependabot workflow)
=> chore: fixing reactivity after refactoring plugins rendering

.github/workflows/pr-preview.yml, .gitignore
Issue:
- https://github.com/openscd/open-scd/issues/1508
=> feat: set up PR preview

.github/workflows/build-and-deploy.yml
Trigger build and deploy on all source code changes
=> build: Trigger deploy on all source code changes

packages/core/package.json
Release-As: 0.34.0
Raise core version and trigger github release
=> chore: Release 0.34.0, core 0.1.2

.github/workflows/release-please.yml, package.json, packages/core/foundation.ts
=> chore: Release 0.34.0, core 0.1.2 attempt 2

.github/workflows/release-please.yml, package-lock.json, package.json, packages/core/foundation.ts
=> chore: Release 0.34.0, core 0.1.2 attempt 3

packages/core/foundation.ts
=> chore: Release 0.34.0, core 0.1.2 attempt 4

package-lock.json, packages/openscd/src/addons/Layout.ts, packages/openscd/src/open-scd.ts, packages/openscd/test/integration/__snapshots__/open-scd.test.snap.js
increase readability of a few places
=> Exploratory Refactoring

packages/openscd/README.md, packages/openscd/src/addons/Layout.ts
Trigger "Add Custom Plugin" dialog using an event.
=> feat(layout): plugin popup event

packages/distribution/manifest.json
=> chore: release 0.36.0

docs/how-to/release.md, release-please-config.json
- Add info about release automation and versioning strategy
- Changes to the release please config: update versions in `packages/distribution/manifest.json`, `packages/core/package.json` and `packages/openscd/package.json`
Closes #1661
=> ci: update versioning in release-please config

packages/distribution/public/xml/IEC_61850-7-2_2007B5.nsd, packages/distribution/public/xml/IEC_61850-7-3_2007B5.nsd, packages/distribution/public/xml/IEC_61850-7-4_2007B5.nsd, packages/openscd/public/md/Validate-template.md, packages/openscd/public/xml/IEC_61850-7-2_2007B5.nsd, packages/openscd/public/xml/IEC_61850-7-3_2007B5.nsd, packages/openscd/public/xml/IEC_61850-7-4_2007B5.nsd, packages/openscd/src/foundation/nsd.ts, packages/openscd/src/translations/de.ts, packages/openscd/src/translations/en.ts, packages/openscd/test/integration/Setting.test.ts, packages/openscd/test/integration/__snapshots__/Setting.test.snap.js, packages/openscd/test/testfiles/nsdoc/IEC_61850-7-2-B-3.nsdoc, packages/openscd/test/testfiles/nsdoc/IEC_61850-7-2.nsdoc, packages/openscd/test/unit/Setting.test.ts, packages/openscd/test/unit/__snapshots__/Setting.test.snap.js, packages/plugins/public/xml/IEC_61850-7-2_2007B5.nsd, packages/plugins/public/xml/IEC_61850-7-3_2007B5.nsd, packages/plugins/public/xml/IEC_61850-7-4_2007B5.nsd, packages/plugins/src/editors/Templates.ts, packages/plugins/src/validators/ValidateTemplates.ts, packages/plugins/src/validators/templates/foundation.ts, packages/plugins/test/integration/editors/templates/__snapshots__/lnodetype-wizard.test.snap.js, packages/plugins/test/integration/validators/ValidateTemplates.test.ts, packages/plugins/test/integration/validators/__snapshots__/ValidateTemplates.test.snap.js, packages/plugins/test/testfiles/templates/dotypes.scd, packages/plugins/test/testfiles/validators/datatypetemplateerrors.scd, packages/plugins/test/testfiles/validators/zeroissues.scd, packages/plugins/test/unit/validators/ValidateTemplates.test.ts
Bumps the versions of NSD files
- IEC 61850_7-4 2007B3 -> IEC 61850_7-4 2007B5
- IEC 61850_7-3 2007B3 -> IEC 61850_7-3 2007B5
- IEC 61850_7-2 2007B3 -> IEC 61850_7-2 2007B5
Closes #1688
=> feat: update nsd files
