- src/open-scd.ts
- src/wizard-dialog.ts
- test/integration/open-scd.test.ts
How do you like it without the dialog? We might avoid some layout problems this way.
> feat(open-scd): remove landing dialog around buttons

- src/Editing.ts
- src/editors/Substation.ts
- src/foundation.ts
- src/open-scd.ts
- src/wizard-dialog.ts
- test/integration/open-scd.test.ts
- test/unit/Editing.test.ts
> feat(open-scd): add project handling including landing dialog

- __snapshots__/bay-editor.md
- __snapshots__/substation-editor.md
- __snapshots__/voltage-level-editor.md
- src/editors/substation/bay-editor.ts
- src/editors/substation/foundation.ts
- src/editors/substation/substation-editor.ts
- src/editors/substation/voltage-level-editor.ts
- src/translations/de.ts
- src/translations/en.ts
Limited to icon buttons in header of editors. Other icon buttons considered to be clear.  Decided to wait for further feedback
Closes #57
> feat(substation/editors): add tooltip to header icon buttons

- src/Logging.ts
I needed the log from the schema validator and found it very disturbing that long messaged were cut off. The tooltip is a quick solution. We might discuss how we want to solve this on a long run.
> feat(logging): add tooltip to make long string readable

- src/triggered/CommunicationMapping.ts
> fix(communicationmapping): ClientLN handling for LNs reside in AccessPoint

- src/open-scd.ts
- test/integration/open-scd.test.ts
> fix(open-scd): fix createNewProject for Edition 2

- src/wizard-dialog.ts
- test/unit/wizard-dialog.test.ts
Christian, 
The fix for the bug we found, when we don't want to close the wizard, for instance because a field was incorrect, and no WizardActions where returned, the action on the button should not be removed.
> fix(wizard-dialog): remove button actions only after action was successful

- __snapshots__/open-scd.md
- src/Logging.ts
The "reset" LogEvent kind accidentally introduced a new filter `mwc-icon-button` to the log dialog, which was invisible (no icon), but prevented users from filtering for only "info" kind log entries.
> fix(logging): remove superfluous invisible reset filter

- src/wizards/commmap-wizards.ts
This fix for now is to ignore all `ExtRefs` that have no valid source. 
Closes #297
> fix(wizard/commap): neglect ExtRef without valid source

- __snapshots__/BDA wizarding editing integration.md
- __snapshots__/DA wizarding editing integration.md
- src/translations/de.ts
- src/translations/en.ts
- src/wizards/controlwithiedname.ts
- test/integration/editors/templates/lnodetype-wizard.test.ts
> Improve capitalisation in some cases, correct typos in English, add translation for menu.new

- __snapshots__/bay-editor.md
- __snapshots__/substation-editor.md
- __snapshots__/voltage-level-editor.md
- __snapshots__/zeroline-pane.md
- src/editor-container.ts
- src/zeroline-pane.ts
- src/zeroline/bay-editor.ts
- src/zeroline/substation-editor.ts
- src/zeroline/voltage-level-editor.ts
- test/unit/editor-container.test.ts
> fix(editor-container): some UI related issues

- src/Editing.ts
- src/editors/Communication.ts
- src/editors/Templates.ts
- src/editors/communication/connectedap-editor.ts
- src/editors/communication/subnetwork-editor.ts
- src/editors/substation/guess-wizard.ts
- src/editors/templates/datype-wizards.ts
- src/editors/templates/dotype-wizards.ts
- src/editors/templates/enumtype-wizard.ts
- src/editors/templates/foundation.ts
- src/editors/templates/lnodetype-wizard.ts
- src/foundation.ts
- src/menu/ImportIEDs.ts
- src/menu/SubscriberInfo.ts
- src/wizards/address.ts
- src/wizards/bay.ts
- src/wizards/bda.ts
- src/wizards/clientln.ts
- src/wizards/conductingequipment.ts
- src/wizards/da.ts
- src/wizards/lnode.ts
- src/wizards/substation.ts
- src/wizards/voltagelevel.ts
- test/integration/Editing.test.ts
- test/mock-editor-logger.ts
- test/testfiles/Editing.scd
- test/unit/Editing.test.ts
Leaving reference optional allows to determine from `getReference` on action. The beauty here is that we still can define reference in action creation where fit better. Thanks @ca-d for this nice idea!
Closes #321
> refactor(foundation): make reference optional 

- __snapshots__/Single Line Diagram drawing.md
- src/editors/SingleLineDiagram.ts
- src/editors/singlelinediagram/foundation.ts
- src/editors/singlelinediagram/sld-drawing.ts
- src/icons.ts
- src/zeroline/foundation.ts
- test/testfiles/valid2007B4withSubstationXY.scd
- test/unit/editors/singlelinediagram/foundation.test.ts
- test/unit/editors/singlelinediagram/sld-drawing.test.ts
The PR contains some steps:
First, I exchanged the name in the `<g>` element with the identity string. The first is a global identifier, the second not. @Flurb this was a great idea from you to write them into the `<g>` as we can make use of the selector functions that - with the `tagName` and `identifier` - can give the element in the doc. This allows us to very, very simple add user interaction. E.g. we even could reuse all the wizards that we use in the Substation plug-in editor to edit create manipulate add LNode and all the beautiful things we do :)
Also I 
1.) I decoupled the connectivity node icon from the conducting equipment icons
2.) added a two winding power transformer icon
3.) realized that substation must be valid parent as PowerTransformer can be direct child of Substation: …
> feat(SingleLineDiagram): add PowerTransformer to the SLD

- src/editors/SingleLineDiagram.ts
- src/editors/singlelinediagram/sld-drawing.ts
- src/icons.ts
- src/translations/de.ts
- src/translations/en.ts
- src/wizards/connectivitynode.ts
- src/wizards/terminal.ts
- src/wizards/wizard-library.ts
Information is read-only.
Saving is disabled, because you can't just change the pathName of a Connectivity Node for example.
Because then, you have to change the terminals as well of connected Conducting Equipments for example.
So editing is disabled, just viewing.
However, with Pro mode you can edit of course.
But I assume people using Pro mode know what they are doing.
> Added terminal and Connectivity Node information

- src/action-icon.ts
- test/unit/__snapshots__/action-icon.test.snap.js
After having a hard time styling the parents of action-icon based editor to make sure that the footer transform and fab action icon transform does not affect outlines, I found this to be a solution that works everywhere and is independent of parent CSS.
> style(action-icon): make sure footer transform does not effect parent CSS

- src/wizards/fcda.ts
- test/integration/wizards/fcda-wizarding-editing-integration.test.ts
- test/unit/wizards/fcda.test.ts
When creating a `FCDA` element, we add an `ìedName` attribute to this element which is not defined within `FCDA` and therefor is schema invalid.
Closes #445
> fix(wizards/fcda): remove incorrect iedName from FCDA

- src/action-icon.ts
- src/zeroline-pane.ts
I wanted to allow a longer IED name in the substation editor (about 12 characters). In my experience, IED names can be long, and not all substations have primary equipment in the SCD file and the substation editor is an important entry point in open-scd.
See comments in #375.
Result:
I'm not very up with modern CSS frameworks and so I may be breaking a host of rules here in which case this PR can be closed without me being very concerned :wink:
> style(zeroline/ied-editor): allow longer IED name

- src/editors/SingleLineDiagram.ts
- src/editors/singlelinediagram/foundation.ts
- src/editors/singlelinediagram/sld-drawing.ts
- src/schemas.ts
- src/translations/de.ts
- src/translations/en.ts
- test/unit/editors/singlelinediagram/sld-drawing.test.ts
- test/unit/schema.test.ts
- Added Substation Selector in the SLD Editor. This was needed, because with multiple substations the elements are overlapping, because all substations start drawing from position 0,0.
- Fixed drawing Connectivity Nodes when there is no SubstationName/VoltgaeLevelName/BayName attribute on the Terminal. These attributes are optional in the XML and should only be check if available.
- Refactoring drawing the SVG for a Substation. 
Pull Request resolves #416
> feat(editors/SingleLineDiagram): allow selecting the Substation element

- src/editors/SingleLineDiagram.ts
- src/editors/singlelinediagram/foundation.ts
- src/editors/singlelinediagram/sld-drawing.ts
- src/editors/singlelinediagram/wizards/bay.ts
- src/editors/singlelinediagram/wizards/conductingequipment.ts
- src/editors/singlelinediagram/wizards/foundation.ts
- src/editors/singlelinediagram/wizards/powertransformer.ts
- src/editors/singlelinediagram/wizards/wizard-library.ts
- src/translations/de.ts
- src/translations/en.ts
- src/wizards/bay.ts
- src/wizards/conductingequipment.ts
- src/wizards/powertransformer.ts
- test/unit/editors/singlelinediagram/foundation.test.ts
- test/unit/editors/singlelinediagram/sld-drawing.test.ts
- test/unit/editors/singlelinediagram/wizards/__snapshots__/bay.test.snap.js
- test/unit/editors/singlelinediagram/wizards/__snapshots__/conductingequipment.test.snap.js
- test/unit/editors/singlelinediagram/wizards/__snapshots__/powertransformer.test.snap.js
- test/unit/editors/singlelinediagram/wizards/bay.test.ts
- test/unit/editors/singlelinediagram/wizards/conductingequipment.test.ts
- test/unit/editors/singlelinediagram/wizards/foundation.test.ts
- test/unit/editors/singlelinediagram/wizards/powertransformer.test.ts
- test/unit/editors/singlelinediagram/wizards/wizard-library.test.ts
- test/unit/wizards/__snapshots__/powertransformer.test.snap.js
- test/unit/wizards/foundation.ts
- test/unit/wizards/powertransformer.test.ts
Extend existing Wizards for Busbar/ConductingEquipment/PowerTransformer in SLD to make it possible to change the X and Y Coordinate for a component. This will be reflected in the SLD directly.
Also made some changes to drawing the SLD to minimize the overlap of bays/busbars/powertransformers. If 2 bays overlap each other some click events won't be trigger, because the elements are hidden by the other bay overlapping the element.
> feat(editors/SingleLineDiagram): allow updating X/Y coordinates in SLD for Busbar/ConductingEquipment/PowerTransformer

- src/editors/ied/da-container.ts
- src/editors/ied/do-container.ts
- src/editors/ied/ln-container.ts
- test/unit/editors/ied/__snapshots__/da-container.test.snap.js
- test/unit/editors/ied/__snapshots__/do-container.test.snap.js
- test/unit/editors/ied/__snapshots__/ln-container.test.snap.js
- test/unit/editors/ied/da-container.test.ts
- test/unit/editors/ied/do-container.test.ts
- test/unit/editors/ied/ln-container.test.ts
- web-test-runner.config.mjs
@Flurb  as you did not like the toggle function I tried to refactor. What do you think.
I do get snapshot updates that I cannot interpret. Maybe you can have a look.
> refactor(ied/da-container,do-container): code improvements

- src/editors/ied/ldevice-container.ts
- test/testfiles/valid2007B4withIEDModifications.scd
- test/unit/editors/ied/__snapshots__/ldevice-container.test.snap.js
- test/unit/editors/ied/ldevice-container.test.ts
> feat(editors/ied): Add toggle for LDevice child elements

- src/foundation.ts
- src/wizards/reportcontrol.ts
- src/zeroline-pane.ts
- src/zeroline/ied-editor.ts
- test/integration/wizards/reportcontrol-wizarding-editing.test.ts
- test/testfiles/wizards/reportcontrol.scd
- test/unit/wizards/__snapshots__/reportcontrol.test.snap.js
> feat(wizards/reportcontrol): access edit wizard from select wizard

- src/editors/IED.ts
- src/editors/SingleLineDiagram.ts
- test/integration/editors/IED.test.ts
- test/integration/editors/__snapshots__/IED.test.snap.js
If a IED or Substation was selected in the drop-down box and next a Element was edited using one of the Wizards the selection was lost and the first element of the list was again selected.
The solution for now is to save the selection outside the LitElement, preventing it being lost after being re-created.
> fix(editors): In IED and SLD Editors fixed preserving the selection (IED or Substation)

- src/editors/SingleLineDiagram.ts
- src/icons.ts
- src/wizards/conductingequipment.ts
- src/zeroline/foundation.ts
- test/testfiles/conductingequipmentwizard.scd
- test/unit/editors/substation/conductingequipmentwizard.test.ts
Closes #459 by providing an earth switch icon and using this in the various editors and wizards.
The logic for ESR detection shouldn't be in multiple places but it may be like this for a very good reason so I have not modified it.
In the SLD:
In the Substation Editor:
I'll be happy to take a review and make modifications.
I've tried to keep the icon square while retaining the stroke width but happy to take some feedback as to whether this is visually acceptable. Another option to introduce spacing might be to make the switch portion smaller or the earth symbol smaller.
> refactor(editors/substation/conductingequipment): add earth-switch symbol

- src/wizards/fcda.ts
- test/integration/wizards/fcda-wizarding-editing-integration.test.ts
- test/unit/wizards/fcda.test.ts
Close #497 
Sorry @ca-d. I should have added a description of the PR here. With this fix I wanted to prevent that an empty string is set for the attribute `lnInst` within the element `FCDA`. To do so, the action function checks if the referenced `LN` or `LN0` has a `inst` defined AND if it is not an empty string. In these cases `lnInst` must be `inst`. In all other cases, `lnInst` must be missing within `FCDA`.
> fix(wizards/fcda): make sure lnInst is non empty string

- src/open-scd.ts
The fact that the landing buttons only look nice if I have exactly two of them has been bothering me for a long time.
This patch finally fixes that by making the display of the landing buttons reactive.
> style: make landing buttons reactive

- src/translations/de.ts
- src/translations/en.ts
- src/wizards/address.ts
- src/wizards/sampledvaluecontrol.ts
- src/wizards/smv.ts
- test/foundation.ts
- test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts
- test/unit/wizards/__snapshots__/address.test.snap.js
- test/unit/wizards/__snapshots__/gse.test.snap.js
- test/unit/wizards/__snapshots__/smv.test.snap.js
- test/unit/wizards/smv.test.ts
> feat(wizards/smv): add edit wizard and allow access from sampledvaluecontrol wizard

- src/editors/templates/datype-wizards.ts
- src/editors/templates/dotype-wizards.ts
- src/editors/templates/enumtype-wizard.ts
- src/editors/templates/lnodetype-wizard.ts
- src/wizards/abstractda.ts
Working in template wizard can be confusing, especially when cancel means starting from scratch. That is why the subwizard option is perfect here.
> refactor(editors/template): use subwizard option

- src/editors/templates/datype-wizards.ts
- src/editors/templates/enumtype-wizard.ts
Creating element without NS definition is not valid for this specific XML files we are working with.
> fix(editors/template): create element with NS definition

- src/Editing.ts
- src/foundation.ts
- test/integration/Editing.test.ts
- test/unit/Editing.test.ts
We want to introduce a new EditorAction `Update` that allows to keep the `element` in the DOM and use its reference when the identity string cannot be use - e.g. name attribute must be exchanged. The action allows exchange the attributes of `element` with `newAttributes`. Updating children of `element` is out of scope, but can be done using `Create` and `Delete` as those can now be user for any kind of `Node`.
> feat(foundation): add EditorAction type Update

- src/editors/subscription/elements/goose-message.ts
- src/editors/subscription/elements/ied-element.ts
- src/editors/subscription/foundation.ts
- src/editors/subscription/publisher-goose-list.ts
- src/editors/subscription/subscriber-ied-list.ts
- src/foundation.ts
- test/unit/editors/subscription/elements/ied-element.test.ts
Most of the changed lines are due to code linting. We have a hook on pushing from git bash. You can use a prettier in VSCode instead.
- I changed the actions to complex action. Please add the title and its translation, as this might be something I want to discuss with @randy993 
- I moved the action definition to the plugins foundation as they are only used within this plugin
- I fixed the import statements. Please make sure that all web-component definitions are imported also the @materail one
> refactor: use complex actions to subscribe and unsubscribe

- src/Editing.ts
- src/translations/de.ts
- src/translations/en.ts
- test/testfiles/Editing.scd
- test/unit/Editing.test.ts
The attribute `id` defined for the elements `LNodeType`, `DOType`, `DAType` and `EnumType` must be unique globally. This PR adds this check into the default `checkValidaty` function for `Create`, `Replace` and `Update` action events.
> feat(Editing): check globally for ID uniqueness

- src/foundation.ts
- src/wizard-dialog.ts
- test/unit/__snapshots__/wizard-dialog.test.snap.js
- test/unit/wizard-dialog.test.ts
Triggered by @danyill I was thinking how to get rid of the buttons in the wizard content. @danyill rightly so pointed out that those buttons/actions should be allocated like the primary/secondary action not in the content of the wizard. 
This mock puts the in a menu that can be open on icon-button click in the right upper corner of the wizard. You can test it working with `EnumType`s in the template editor: 
1. go to Template editor
2. go to EnumType list
3. click on any of the list items
4. see the more vert icon button on the right upper corner
5. click and try the behaviour
6. compare to e.g. DAType list -> wizard
@Sander3003 @Flurb @dlabordus @ca-d @danyill I would be curious about your take on it. If this is a viable option, I would get rid of the buttons in wizard content
> feat(wizard-dialog): allow used-defined actions in menu

- src/editors/templates/lnodetype-wizard.ts
- test/integration/editors/templates/__snapshots__/lnodetype-wizard.test.snap.js
- test/integration/editors/templates/lnodetype-wizard.test.ts
Proceeding to remove mwc-button from wizard-dialog content
> refactor(editors/templates/lnodetype): use menu actions

- src/editors/templates/dotype-wizards.ts
- test/integration/editors/templates/__snapshots__/dotype-wizarding.test.snap.js
- test/integration/editors/templates/dotype-wizarding.test.ts
- test/integration/wizards/da-wizarding-editing.test.ts
Proceeding to remove `mwc-button` from `wizard-dialog`s content
> refactor(editors/template/dotype): dotype/sdo wizards use menu actions

- src/wizards/dataset.ts
- test/unit/wizards/__snapshots__/dataset.test.snap.js
- test/unit/wizards/dataset.test.ts
The last refactor that removes `mwc-button` from `wizard-dialog`. finally
> refactor(wizards/dataset): remove mwc-button from wizard content

- src/Logging.ts
- src/Setting.ts
- src/translations/de.ts
- src/translations/en.ts
- test/integration/Setting.test.ts
- test/integration/__snapshots__/Setting.test.snap.js
- test/integration/__snapshots__/open-scd.test.snap.js
- test/integration/open-scd.test.ts
- test/testfiles/nsdoc/IEC_61850-7-2.nsdoc
- test/testfiles/nsdoc/invalid.nsdoc
- test/testfiles/nsdoc/wrong-version.nsdoc
- test/testfiles/settingTest.nsdoc
- test/unit/Setting.test.ts
- test/unit/foundation/nsdoc.test.ts
For CoMPAS we needed the loading to be done through a Custom Event, as it was original agreed. 
This way the logic for loading doesn't need to be duplicated.
> refactor(setting/nsdoc): Loading NSDoc Files through Custom Event

- src/filtered-list.ts
- test/unit/filtered-list.test.ts
Close #646 
This PR is in between fix and feat. The `filtered-list` was not designed to filter nested list items. However, in dialogs the space is so limited that we do use `abbr` like in the diagnosis dialog. 
With this PR I propose to change the filter strategy of the `filtered-list` a bit an allow to filter for any nested `mwc-...-list-item`.
> fix(filtered-list): allow filter nested mwc-...-list-item s

- src/Editing.ts
- src/editors/IED.ts
- src/editors/SingleLineDiagram.ts
- src/translations/de.ts
- src/translations/en.ts
- src/wizards/foundation/actions.ts
- src/wizards/foundation/references.ts
- src/wizards/ied.ts
- src/wizards/substation.ts
- test/testfiles/wizards/substation.scd
- test/unit/wizards/__snapshots__/ied.test.snap.js
- test/unit/wizards/__snapshots__/substation.test.snap.js
- test/unit/wizards/foundation.ts
- test/unit/wizards/foundation/references.test.ts
- test/unit/wizards/ied.test.ts
- test/unit/wizards/powertransformer.test.ts
- test/unit/wizards/substation.test.ts
> fix(editors): Changed selectors in Substation and IED Editors and updated IED and Substation Wizards.

- src/translations/de.ts
- src/translations/en.ts
- src/wizards/address.ts
- src/wizards/foundation/scl.ts
- src/wizards/gse.ts
- src/wizards/gsecontrol.ts
- src/wizards/smv.ts
- test/integration/wizards/gsecontrolwizarding-editing.test.ts
- test/testfiles/wizards/gsecontrol.scd
- test/unit/wizards/__snapshots__/gsecontrol.test.snap.js
- test/unit/wizards/address.test.ts
- test/unit/wizards/foundation/scl.test.ts
- test/unit/wizards/gsecontrol.test.ts
Create wizards for the `GSEControl` elements. Some implementation details:
When adding a `GSEControl` a `GSE` element must be added to the `Communication` section as well. This is true only if there is a `ConnectedAP` for the `AccessPoint` where the `Server` resides in. If there is no `ConnectedAP` no `GSE` element must be added. The way it is implemented now: when `ConnectedAP` is present the second page of the create wizard allows to specify the `GSE` element. Otherwise this page is not rendered and the create wizard consists of only two wizard pages. To test delete all `SubNetwork` elements in the Communication plugin.
> feat(wizards/gsecontrol): add create wizards

- src/translations/de.ts
- src/translations/en.ts
- src/wizards/reportcontrol.ts
- test/unit/wizards/__snapshots__/reportcontrol.test.snap.js
> feat(wizards): Changed label of rptID

- src/zeroline/subfunction-editor.ts
- test/testfiles/zeroline/functions.scd
- test/unit/zeroline/__snapshots__/function-editor.test.snap.js
- test/unit/zeroline/__snapshots__/subfunction-editor.test.snap.js
- test/unit/zeroline/function-editor.test.ts
- test/unit/zeroline/subfunction-editor.test.ts
The second of the two to render read-only `Function` and `SubFunction` editors within the Substation editor.
> feat(zeroline): add read-only subfuction-editor

- src/translations/de.ts
- src/translations/en.ts
- src/zeroline-pane.ts
- src/zeroline/bay-editor.ts
- src/zeroline/foundation.ts
- src/zeroline/function-editor.ts
- src/zeroline/subfunction-editor.ts
- src/zeroline/substation-editor.ts
- src/zeroline/voltage-level-editor.ts
- test/testfiles/zeroline/functions.scd
- test/unit/__snapshots__/zeroline-pane.test.snap.js
- test/unit/zeroline-pane.test.ts
- test/unit/zeroline/__snapshots__/bay-editor.test.snap.js
- test/unit/zeroline/__snapshots__/function-editor.test.snap.js
- test/unit/zeroline/__snapshots__/subfunction-editor.test.snap.js
- test/unit/zeroline/__snapshots__/substation-editor.test.snap.js
- test/unit/zeroline/__snapshots__/voltage-level-editor.test.snap.js
- test/unit/zeroline/bay-editor.test.ts
- test/unit/zeroline/function-editor.test.ts
- test/unit/zeroline/subfunction-editor.test.ts
- test/unit/zeroline/substation-editor.test.ts
- test/unit/zeroline/voltage-level-editor.test.ts
The first of two PRs that will allow seeing read-only `Function` element in Substation editor. This shall be a possible  an entry point for functional naming in OpenSCD.
> feat(substation): read only Function and SubFunction container

- src/editors/substation/eq-sub-function-editor.ts
- test/testfiles/zeroline/functions.scd
- test/unit/editors/substation/__snapshots__/eq-function-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/eq-sub-function-editor.test.snap.js
- test/unit/editors/substation/eq-sub-function-editor.test.ts
The last to have all the function types visible as read-only panes
> feat(editors/substation): add read-only eq-sub-function-editor

- src/editors/substation/bay-editor.ts
- src/editors/substation/conducting-equipment-editor.ts
- src/editors/substation/eq-function-editor.ts
- src/editors/substation/eq-sub-function-editor.ts
- src/editors/substation/foundation.ts
- src/editors/substation/function-editor.ts
- src/editors/substation/powertransformer-editor.ts
- src/editors/substation/sub-function-editor.ts
- src/editors/substation/substation-editor.ts
- src/editors/substation/voltage-level-editor.ts
- test/testfiles/zeroline/functions.scd
- test/unit/editors/substation/__snapshots__/bay-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/eq-function-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/eq-sub-function-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/function-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/powertransformer-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/sub-function-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/substation-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/voltage-level-editor.test.snap.js
- test/unit/editors/substation/bay-editor.test.ts
- test/unit/editors/substation/conducting-equipment-editor.test.ts
- test/unit/editors/substation/eq-function-editor.test.ts
- test/unit/editors/substation/eq-sub-function-editor.test.ts
- test/unit/editors/substation/powertransformer-editor.test.ts
- test/unit/editors/substation/sub-function-editor.test.ts
- test/unit/editors/substation/substation-editor.test.ts
- test/unit/editors/substation/voltage-level-editor.test.ts
The first of three requests that cover the issue #707 
1. ~~transform CondunctingEquipment and PowerTransformer to action-pane on function filter disabled~~
2. ~~show `EqFunction` element within ConductingEquipment and PowerTransformer~~
3. ~~show `EqSubFunction` within `EqFunction`~~
> feat(editors/substation): show read-only `EqFunction` and `SubEqFunction`

- src/menu/SubscriberInfo.ts
- test/testfiles/subscriberinfo2007.scd
- test/unit/editors/subscriberinfo.test.ts
I have found this bug preparing my presentation and just fixed it right away:
> When creating a `IEDName` element referencing `ExtRef` within `LN0` parent element in other IEDs the standard says the `lnInst` must be missing. At the moment we however do set it to a empty string.
> fix(menu/subscriberinfo): fix lnInst attribute for lnClass LLN0

- src/action-icon.ts
- src/editors/substation/l-node-editor.ts
- test/unit/editors/substation/__snapshots__/l-node-editor.test.snap.js
With read-only `l-node-editor` it became obvious that we need to disable transform CSS rules designed to adapt to floating action buttons. This PR is adding this feature to the `action-icon` component
> feat(action-icon): add hideActions property

- src/action-pane.ts
- test/unit/action-pane.test.ts
Closes #714 
This PR is removing h5 and h6 from `action-pane`. The headings in IED editor and the Substation editor are more readable without drawback as I think. What do you think? @danyill @Sander3003 @dlabordus @Flurb
> refactor(action-pane): remove h5 and h6 max to h4

- src/editors/substation/function-editor.ts
- src/wizards/function.ts
- src/wizards/wizard-library.ts
- test/integration/editors/substation/function-editor.test.ts
- test/testfiles/zeroline/functions.scd
- test/unit/editors/substation/__snapshots__/function-editor.test.snap.js
- test/unit/wizards/__snapshots__/function.test.snap.js
- test/unit/wizards/function.test.ts
This is one of four PRs covering #332
> feat(wizards/function): add edit wizard

- src/editors/templates/datype-wizards.ts
- src/editors/templates/dotype-wizards.ts
- src/editors/templates/enumtype-wizard.ts
- src/editors/templates/lnodetype-wizard.ts
- src/foundation.ts
- src/wizard-dialog.ts
- src/wizards/bda.ts
- src/wizards/da.ts
- src/wizards/dataset.ts
- src/wizards/gsecontrol.ts
- src/wizards/ied.ts
- src/wizards/reportcontrol.ts
- src/wizards/sampledvaluecontrol.ts
This is a small refactor as an output of a discussion between @ca-d and me. We were trying to trigger a wizard, not a sub-wizard from menu actions and thought the API as it is not flexible enough. This is therefore our new proposal :)
> refactor(foundation): change menu action API

- src/editors/substation/l-node-editor.ts
- test/integration/editors/substation/l-node-editor-wizarding-editing.test.ts
- test/unit/editors/substation/__snapshots__/l-node-editor.test.snap.js
> feat(editor/substation/l-node-editor): add remove button

- src/wizard-checkbox.ts
- src/wizard-select.ts
- src/wizard-textfield.ts
- test/unit/wizard-checkbox.test.ts
- test/unit/wizard-select.test.ts
- test/unit/wizard-textfield.test.ts
The components we are providing `wizard-textfield`, `wizard-select` and `wizard-checkbox` had an incorrect behaviour when `disabled`.
Closes #783 .
> fix(wizard-diagram, wizard-select, wizard-checkbox):  disabled attribute

- src/editors/cleanup/control-blocks-container.ts
- src/editors/cleanup/datasets-container.ts
- test/unit/editors/cleanup/__snapshots__/control-blocks-container.test.snap.js
This is the CSS solution to #746. I quite like it. But I would like some feedback.
I haven't applied for the dataset cleanup yet until we can decide between this and the other PR.
> feat(editors/cleanup) Provide appearing/disappearing edit button on hover

- src/editors/substation/l-node-editor.ts
- src/foundation.ts
- src/wizards/lnode.ts
- test/integration/editors/substation/l-node-editor-wizarding-editing.test.ts
- test/testfiles/zeroline/functions.scd
- test/unit/editors/substation/__snapshots__/l-node-editor.test.snap.js
- test/unit/foundation.test.ts
Closes #741 
This is a useful tool when working on functions with multiple logical node instances of the same `LNodeType` e.g. a distance function that consists of 5 to 7 zones where each zone is represented with a logical node `PDIS` and usually is the same structure.
> feat(wizards/substation/l-node-editor): add duplicate button

- src/editors/Templates.ts
- test/integration/editors/templates/Templates.test.ts
Closes #824 . 
Simple thing, but to remember for the future. When using `@selected` on a `mwc-list` and therefore also `filtered-list` will only fire when the selection has been changed. For the used case we have here: reacting on any click in the list `action` is the one to go for.
> fix(editors/template): make sure that edit wizards are always opened

- public/js/plugins.js
- src/editors/Publisher.ts
- src/editors/publisher/data-set-editor.ts
- src/editors/publisher/gse-control-editor.ts
- src/editors/publisher/report-control-editor.ts
- src/editors/publisher/sampled-value-control-editor.ts
- test/integration/__snapshots__/open-scd.test.snap.js
- test/unit/editors/Publisher.test.ts
- test/unit/editors/__snapshots__/Publisher.test.snap.js
- test/unit/editors/publisher/__snapshots__/data-set-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/gse-control-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/report-control-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/sampled-value-control-editor.test.snap.js
- test/unit/editors/publisher/data-set-editor.test.ts
- test/unit/editors/publisher/gse-control-editor.test.ts
- test/unit/editors/publisher/report-control-editor.test.ts
- test/unit/editors/publisher/sampled-value-control-editor.test.ts
This PR is covering issues #709 #710 and #711 in showing a filterable list of `ReportControl`, `GSEControl` and `SampledValueControl` elements. I also took into account the discussion #561 and added defined `DataSet` elements as well. This will allow users to follow a workflow where `DataSet` element are created independently of control blocks and a re combined with those in a lager engineering step or even online.
> feat(editors/publisher): filter for control blocks and DataSets

- src/Hosting.ts
- src/Plugging.ts
- src/open-scd.ts
- test/integration/__snapshots__/open-scd.test.snap.js
Close #842 
Regression tests are missing here, sorry. In `open-scd` we do not have a regression test that would allow testing this specific situation. We should take it into account in `open-scd-core`.
The solution was to make menu plugin content the next sibling of it, `list-item` not its child. Doing so, a click on the content is not interpreted as a click in the list-item that triggers the run method.
> fix(Pluggin/Hosting): allocate menu plugin content next to its list item

- public/js/plugins.js
- src/foundation.ts
- src/menu/VirtualTemplateIED.ts
- src/menu/virtualtemplateied/foundation.ts
- test/integration/__snapshots__/open-scd.test.snap.js
- test/testfiles/virtualied/specificfromfunctions.ssd
- test/unit/menu/VirtualTemplateIED.test.ts
- test/unit/menu/__snapshots__/VirtualTemplateIED.test.snap.js
- test/unit/menu/virtualtemplateied/__snapshots__/foundation.test.snap.js
- test/unit/menu/virtualtemplateied/foundation.test.ts
This is it, the plugin that allows to automatically create a virtual template IED - name `SPECIFICATION` - based on the function structure in the substation section. 
I decided to pack it into a menu type plugin for not. When we will extend the functionality around the virtual IED creation in the future, we can convert it into an editor type plugin. 
> To test, use the *.ssd file in the testfiles folder.
Closes #742
> feat(menu/VirtualTemplateIED): automatically create virtual IEDs

- src/editors/substation/bay-editor.ts
- src/editors/substation/conducting-equipment-editor.ts
- src/editors/substation/eq-function-editor.ts
- src/editors/substation/eq-sub-function-editor.ts
- src/editors/substation/function-editor.ts
- src/editors/substation/ied-editor.ts
- src/editors/substation/l-node-editor.ts
- src/editors/substation/powertransformer-editor.ts
- src/editors/substation/sub-function-editor.ts
- src/editors/substation/substation-editor.ts
- src/editors/substation/voltage-level-editor.ts
- src/editors/substation/zeroline-pane.ts
Close #850 
I did not add regression tests as I think they cannot be done without visual regression tests. Btw @ca-d the snapshot type regression tests you did for the `Communication` editor fixing this issue are incorrect. I did not have a close enough look at those during review. You can see by looking at the number of children. This never differs, independent whether one is deleted or added.
> fix(editors/substation): update on action

- src/Editing.ts
This fixes a recently introduced bug in `Editing` where after committing an editor action the auto validation fails because the doc is empty at the point where the validation starts.
Resolves #880 .
> fix(editing): failing auto-validation after editor actions

- src/editors/SingleLineDiagram.ts
Sorry for the reformatting, gives a lot of changes.
But the main change is replacing 'firstUpdated()' with 'updated(...)' to also redraw the SVG when the document changes.
The problem occurs when already on the SLD Tab and a new document is loaded, the change isn't visible.
Also in CoMPAS this gives more problems when the Auto Alignment is called, because the document is reloaded with the new coordinates.
> fix(editor/SingleLineDiagram): Fixed redrawing when new document loaded

- src/wizards.ts
The merge wizard was implemented before our "choose a valid position
automatically" feature was implemented for insert and move actions in
Editing (`reference: undefined`).
Therefore, all insert actions fired by the merge wizard insert the
element at as the parent's last child, resulting in schema invalid files
in many cases (e.g. insert a Substation section in a file with an IED or
DataTypeTemplates). This fixes that issue, making our Merge and
UpdateSubstation plugins schema compliant.
> fix(mergeWizard): insert element at valid position

- src/Editing.ts
- test/unit/Editing.test.ts
After committing an empty complex action (e.g. clicking "merge" in a
merge wizard without any additions or deletions selected) the `Editing`
mixin needlessly dispatches a ValidateEvent causing lengthy validation
of an already validated document. This fixes that issue.
> fix(editing): don't validate after no-op action

- src/editors/publisher/data-set-editor.ts
- src/editors/publisher/gse-control-editor.ts
- src/editors/publisher/report-control-editor.ts
- src/editors/publisher/sampled-value-control-editor.ts
- src/editors/subscription/goose/goose-list.ts
- src/editors/subscription/goose/subscriber-list.ts
- src/editors/subscription/sampledvalues/smv-list.ts
- src/editors/subscription/sampledvalues/subscriber-list.ts
- src/filtered-list.ts
- test/integration/editors/subscription/goose/__snapshots__/GooseControlSubscription.test.snap.js
- test/integration/editors/subscription/sampledvalues/__snapshots__/SampledValuesSubscription.test.snap.js
- test/unit/editors/publisher/__snapshots__/data-set-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/gse-control-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/report-control-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/sampled-value-control-editor.test.snap.js
- test/unit/editors/subscription/goose/__snapshots__/goose-list.test.snap.js
- test/unit/editors/subscription/sampledvalues/__snapshots__/smv-list.test.snap.js
- test/unit/filtered-list.test.ts
After two prototypes and some discussion, I decided to change the filter behavior of filtered-list. What has changed is that not only the list item's primary and secondary span is taken into account, but also its value attribute. This has in my opinion the advantage to be simple in design and very flexible for the user to use. As value is not visible, everybody can decide himself what the value can be and therefor also what the user can filter for. 
Best to test is the publisher plugin or both the subscriber plugins :)
> feat(filtered-list): filter on list item value

- src/editors/Publisher.ts
- src/editors/publisher/data-set-editor.ts
- src/editors/publisher/data-set-element-editor.ts
- src/editors/publisher/foundation.ts
- src/editors/publisher/gse-control-editor.ts
- src/editors/publisher/report-control-editor.ts
- src/editors/publisher/sampled-value-control-editor.ts
- src/translations/de.ts
- src/translations/en.ts
- test/unit/editors/publisher/__snapshots__/data-set-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/data-set-element-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/gse-control-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/report-control-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/sampled-value-control-editor.test.snap.js
- test/unit/editors/publisher/data-set-editor.test.ts
- test/unit/editors/publisher/data-set-element-editor.test.ts
- test/unit/editors/publisher/gse-control-editor.test.ts
- test/unit/editors/publisher/report-control-editor.test.ts
- test/unit/editors/publisher/sampled-value-control-editor.test.ts
This PR adds a read only DataSet element editor that shows referenced DataSets for `ReportControl`, `GSEControl`, `SampledValueControl` as well as `DataSet`s itself.
I have not bothered to create issues for this one. I did test a lot of CSS in the PR and therefore no Mock was present.
> feat(editors/publisher): add read only data set element editor

- src/editors/Publisher.ts
- src/editors/publisher/data-set-editor.ts
- src/editors/publisher/data-set-element-editor.ts
- src/editors/publisher/foundation.ts
- src/editors/publisher/gse-control-editor.ts
- src/editors/publisher/report-control-editor.ts
- src/editors/publisher/report-control-element-editor.ts
- src/editors/publisher/sampled-value-control-editor.ts
- test/integration/wizards/reportcontrol-wizarding-editing.test.ts
- test/testfiles/wizards/reportcontrol.scd
- test/unit/editors/publisher/__snapshots__/data-set-element-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/report-control-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/report-control-element-editor.test.snap.js
- test/unit/editors/publisher/data-set-element-editor.test.ts
- test/unit/editors/publisher/report-control-element-editor.test.ts
This one is adding read-only field showing the settings of a `ReportControl` element and its child elements. Per default it is not displayed to save the room for the data set. I am curious on your take on it.
> feat(plugin): add read-only report-control-element-editor

- src/editors/publisher/data-set-editor.ts
- src/editors/publisher/foundation.ts
- src/editors/publisher/gse-control-editor.ts
- src/editors/publisher/report-control-editor.ts
- src/editors/publisher/sampled-value-control-editor.ts
- test/unit/editors/publisher/data-set-editor.test.ts
- test/unit/editors/publisher/foundation.test.ts
- test/unit/editors/publisher/gse-control-editor.test.ts
- test/unit/editors/publisher/report-control-editor.test.ts
- test/unit/editors/publisher/sampled-value-control-editor.test.ts
Reset selection on loading doc with missing selected element. E.g. new doc does not have a specific `ReportControl` because doc is a completely new file lead to a reset of the selection in the `report-control-editor`. This also means when loading another doc that contains the same element, the selection is not reset.
@ca-d `hasChanged` cannot be used because within this function this.selected... cannot be set/reset. I decided to us update as this is run through before re-render.
> refactor(editors/publisher): reset selections with missing reference

- src/editors/publisher/data-set-element-editor.ts
- src/editors/publisher/gse-control-element-editor.ts
- src/editors/publisher/report-control-element-editor.ts
- src/editors/publisher/sampled-value-control-element-editor.ts
- test/unit/editors/publisher/__snapshots__/data-set-element-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/gse-control-element-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/report-control-element-editor.test.snap.js
- test/unit/editors/publisher/__snapshots__/sampled-value-control-element-editor.test.snap.js
Fixes #994 
We decided to disable read-only inputs for now. The main reason is that we will allow editing step by step and it makes sense then to clearly identify what is editable. Thanks for the hint @arulrajirudayasamy
> fix(editors/plugin): disable read-only inputs

- public/md/Home.md
- public/md/Interface.md
- public/md/_Sidebar.md
- src/filtered-list.ts
- test/unit/filtered-list.test.ts
This is just a prototype.
It does allow you to do a nice thing, i.e. line up phases between left and right.
> Add ? and * wildcards to filtered-search, closes #1006.

- src/editors/subscription/later-binding/ext-ref-later-binding-list.ts
- test/integration/editors/GooseSubscriberLaterBinding.test.ts
- test/testfiles/editors/LaterBindingGOOSE2007B4.scd
- test/unit/editors/subscription/later-binding/__snapshots__/ext-ref-laterbinding-list.test.snap.js
- test/unit/editors/subscription/later-binding/ext-ref-laterbinding-list.test.ts
> fix(editors/later-binding): Resolve absent prefix in ExtRef for later binding subscription

- src/Logging.ts
- src/icons/icons.ts
Closes #1035
I'm not sure what was wrong with the previous approach. 
The inline style expression had an extra bracket on the end (from when I modified it to allow toggle buttons in the cleanup editor), but that was not the only cause.
It seems more general to rely on CSS here than inline styles, and that also resolves the issue, so perhaps this is an acceptable fix? (In the cleanup editor I used CSS and didn't add to the colours which had the side-effect of an "undefined" in the styles attribute.)
> fix(Logging) Correct toggle colors in log

- src/editors/subscription/later-binding/ext-ref-later-binding-list.ts
- src/editors/subscription/later-binding/foundation.ts
- test/integration/editors/GooseSubscriberLaterBinding.test.ts
- test/integration/editors/SMVSubscriberLaterBinding.test.ts
- test/testfiles/editors/LaterBindingGOOSE2007B4.scd
- test/testfiles/editors/LaterBindingSMV2007B4.scd
- test/unit/editors/subscription/later-binding/__snapshots__/ext-ref-later-binding-list.test.snap.js
- test/unit/editors/subscription/later-binding/ext-ref-later-binding-list.test.ts
- test/unit/editors/subscription/later-binding/foundation.test.ts
Closes #867 
Check that the selected data and a later binding external reference match in terms of their `CDC` and `bType` specification.
> feat(editors/subscriber/later-binding): add input requirement check

- src/validators/ValidateSchema.ts
- test/integration/validators/ValidateSchema.test.ts
- test/integration/validators/__snapshots__/ValidateSchema.test.snap.js
Due to a simple oversight we are currently not actually caching schema validator workers at all, meaning we instantiate a new worker on each validation, leaking memory and wasting time. This fixes that issue.
This pull request should result in a noticeable performance increase for repeat validations and in less memory usage.
> fix(validate-schema): cache validator workers

- src/editors/subscription/foundation.ts
- test/unit/editors/subscription/__snapshots__/fcda-binding-list.test.snap.js
Closes #1076
The code I am touching was only added recently so the reason may be nearby
I think `ldInst` is almost always part of an FCDA (GSSE being mostly dead/unused) but prefix maybe not, it is optional in Table 22 of IEC 61850-6 Ed 2.1
So I don't fully understand this code path but this should get rid of the word null.
> fix(subscription) Coalesce lack of prefix to empty string, allow no prefix in FCDA description

- src/editors/substation/bay-editor.ts
- src/editors/substation/conducting-equipment-editor.ts
- src/editors/substation/eq-function-editor.ts
- src/editors/substation/eq-sub-function-editor.ts
- src/editors/substation/function-editor.ts
- src/editors/substation/general-equipment-editor.ts
- src/editors/substation/powertransformer-editor.ts
- src/editors/substation/sub-function-editor.ts
- src/editors/substation/substation-editor.ts
- src/editors/substation/voltage-level-editor.ts
> fix: opened menu cut off

- src/filtered-list.ts
- test/unit/filtered-list.test.ts
Closes #1018 
When a document is changed the filtered list doesn't receive a new filtering action, and its internal state appears to become inconsistent.
Only a couple of lines change for the new updated method. This seems like the right place to do this but I am interested and would be grateful for a review.
I noticed an incorrect import which seems to have been added by me and there is a few formatting changes.
I think this is an issue in the Cleanup plugin and probably other places (everywhere where a document update on a filtered list occurs and the filtered list has filter text).
I can't see how to add tests for this so I have not.
> fix(filtered-list) Filter when document changes

- src/editors/substation/conducting-equipment-editor.ts
- src/editors/substation/foundation.ts
- src/editors/substation/powertransformer-editor.ts
- src/editors/substation/sub-equipment-editor.ts
- test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
- test/unit/editors/substation/__snapshots__/powertransformer-editor.test.snap.js
Closes #1129 
Two things that have been fixed
1. by mistake, the container for sub-equipment-editors was declared min size 64px. That is why it looked too strange. This declaration is only necessary for icon type components. `SubEquipment` is never rendered as icon.
2. sub-equipment-editor do not need to be within a container. That is only necessary when grid type display is used. E.g. Bay within VoltageLevel or ConductingEquipment as icon within Bay. In all other cases, just adding it as child editor is enough. `action-pane` will do all the styling.
There is no regression test as I only touched CSS. Just updated snapshots due to the changes html
> fix: styling issue with SubEquipment editor

- src/wizards/eqfunction.ts
- src/wizards/eqsubfunction.ts
Closes #1133 
No test adoption needed as we do not screenshot test wizards. This is once more am argument to do that when we move plungins.
> fix: add missing code editor to edit wizards

- src/editors/substation/guess-wizard.ts
- src/wizards/substation.ts
- test/integration/editors/substation/guess-wizarding-editing.test.ts
Closes #1147 
With the change from async to sync plugin loading that triggered to pass a new doc after every action event. This bug was introduced. The guess function first adds a `Substation` element then the content of the substation itself.
I changed it now to only send one complex action event instead of two.
> fix(substation/guess-wizard): guessed content is added to the substation

- CHANGELOG.md
- manifest.json
- package-lock.json
- package.json
- src/editors/substation/tapchanger-editor.ts
- src/wizards/tapchanger.ts
- test/integration/editors/substation/tapchanger-editor-wizard-editing.test.ts
- test/unit/editors/substation/__snapshots__/tapchanger-editor.test.snap.js
> 973 remove tapchanger

- .github/workflows/build-and-deploy.yml
- .github/workflows/test-and-build.yml
- .github/workflows/test.yml
- README.md
- package-lock.json
- package.json
- updated GitHub Actions
- provide information in readme on the version to use
fixes #918
> chore(update-actions): Update Node from 14.x to 18.x

- src/wizard-dialog.ts
Closes #895
We use `formatXml` to save documents.
Is it dangerous to use it here? Perhaps a little bit.
When OpenSCD modifies elements e.g. datasets, subscriptions or supervision elements, the XML it produces is difficult to view in the Ace editor without manually adding linebreaks. This resolves that.
> feat(wizards): Pretty print XML inside code editor, closes #895

- src/Hosting.ts
- test/integration/__snapshots__/open-scd.test.snap.js
- test/integration/open-scd.test.ts
> fix: reduce items on menu if elsewhere in the UI

- src/wizards/foundation/limits.ts
- test/integration/editors/templates/__snapshots__/dotype-wizarding.test.snap.js
- test/integration/editors/templates/dotype-wizarding.test.ts
> fix(wizards/doTypes): Adjust regular expressions for v flag in template editor

- src/open-scd.ts
Closes #1269
I couldn't find a solution without changing the z-index without more serious DOM modifications.
I have to use `--primary` I think because I am overwriting `--mdc-theme-primary`.
I  quite like this.
> fix(open-scd): Make linear progress bar Github stylez, closes #1269

- src/editors/IED.ts
Closes #1272
Now that we are using the `editCount`  property we must make sure that plugins are not relying on the old behaviour, like this one. As the `doc` is no longer exchanged on each edit we also need to to look for `editCount` in the `updated` method.
For now I just fix this problem, I hope to have a look through other editors where I suspect similar issues may occur and may not be very visible in our test coverage.
> fix(editors/IED): Allow IEDs to be deleted after edit count change

- src/editors/protocol104/wizards/selectDo.ts
- src/editors/publisher/data-set-editor.ts
- src/editors/publisher/foundation.ts
- src/editors/publisher/gse-control-editor.ts
- src/editors/publisher/report-control-editor.ts
- src/editors/publisher/sampled-value-control-editor.ts
- src/editors/templates/datype-wizards.ts
- src/editors/templates/dotype-wizards.ts
- src/editors/templates/enumtype-wizard.ts
- src/editors/templates/lnodetype-wizard.ts
- src/foundation.ts
- src/foundation/ied.ts
- src/menu/CompareIED.ts
- src/menu/ImportIEDs.ts
- src/menu/UpdateDescriptionABB.ts
- src/menu/UpdateDescriptionSEL.ts
- src/menu/UpdateSubstation.ts
- src/menu/VirtualTemplateIED.ts
- src/wizards/clientln.ts
- src/wizards/commmap-wizards.ts
- src/wizards/dataset.ts
- src/wizards/fcda.ts
- src/wizards/foundation/finder.ts
- src/wizards/gsecontrol.ts
- src/wizards/lnode.ts
- src/wizards/reportcontrol.ts
- src/wizards/sampledvaluecontrol.ts
- test/unit/foundation.test.ts
In the course of some `identity`/`selector` bug fixes in `foundation.ts` (e.g. an ExtRef selector issue introduced in #1179 ) , @JakobVogelsang has identified some fundamental shortcomings of our current identities (e.g. `IEDName` identities not including the element's `textContent`) which are impossible to fix while keeping with the `selector` API.
Since we have been looking forward to moving to the `find` API from the `selector` API for a long time anyway for performance reasons (this API allows us to bypass querySelector entirely in the future and switch to much more performant SCL specific search implementations), we propose to make this switch now, before factoring out individual plugins that depend on the legacy `selector` API.
> refactor(foundation): substitute find() for selector()

- .github/workflows/stale-issues-cron.yml
- .github/workflows/stale-issues-manual.yml
- .github/workflows/stale-issues.yml
- docs/decisions/0001-record-architecture-decisions.md
This PR sets up a GitHub action to automatically mark stale issues.
It also add a manual trigger so we can run it manually if we want to test it.
---
please ignore: the `docs/decisions/0001-record-architecture-decisions.md` it shows up because of rebase
> infra: mark stale issues automatically

- .github/workflows/stale-issues.yml
The permissions check does not seem to work in sub-workflows nor is it needed at all.
> fix(ci): remove unneeded permission check

- src/wizards/foundation/dai-field-type.ts
- src/wizards/foundation/enums.ts
- test/integration/wizards/__snapshots__/bda-wizarding-editing.test.snap.js
- test/integration/wizards/__snapshots__/da-wizarding-editing.test.snap.js
- test/unit/wizards/__snapshots__/abstractda.test.snap.js
Closes #1297 
* Added missing DAI bTypes from IEC 61850-6 ed. 2.1
* Updated test snapshots to include added bTypes
* Octet assumed to be no zero padding, no space hexadecimal string value
I think the treatment of Octet bTypes needs some consideration. However, this PR does allow for DAI of bType `ObjectReference` to be edited as requested.
I would appreciate a review, and further refinement if required.
> fix(wizards/foundation): Added missing DAI bTypes

- src/editors/substation/ied-editor.ts
> fix: added editcount to reflect made changes

- .github/workflows/build-and-deploy.yml
The deploy action does not use the `working-directory` default parameter so the full path is needed.
> fix(action): correct source folder

- packages/open-scd/src/editors/protocol104/wizards/address.ts
- packages/open-scd/src/foundation.ts
- packages/open-scd/src/translations/de.ts
- packages/open-scd/src/translations/en.ts
- packages/open-scd/test/unit/editors/protocol104/wizards/address.test.ts
> chore(104): validate IOA number in address-wizard

- .github/workflows/build-and-deploy.yml
The action was running with every change. After the PR it will only run if there is a change in the packges/open-scd folder
> infra: limit github action to open-scd folder

- packages/open-scd/src/editors/protocol104/foundation/cdc.ts
- packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts
> fix(104): change options between different tis when selecting a doi

- .github/workflows/build-and-deploy.yml
- packages/open-scd/README.md
Building and deploying OpenSCD failed, because the package `@openscd/core` hasn't been built yet.
This step has been added.
Also, the documentation (TypeDoc) from core will be pushed to `packages/open-scd/build/core-doc`, so it will be published as well
> fix(gh-action): build-and-deploy should first build core before building OpenSCD

- packages/open-scd/src/editors/ied/da-wizard.ts
- packages/open-scd/src/editors/ied/do-wizard.ts
- packages/open-scd/test/unit/editors/ied/__snapshots__/da-wizard.test.snap.js
- packages/open-scd/test/unit/editors/ied/__snapshots__/do-wizard.test.snap.js
@DavoodSooran noticed an error in the do-wizard and da-wizard. In these wizards there's a `logical node description` field with the lnclass value. This PR changed the field title from  `Logical node description` to  `Logical node class`
> fix: do and da wizard lnclass textfield correction

- .github/workflows/release-please.yml
> fix: add node release type and core path

- packages/open-scd/src/addons/Settings.ts
- packages/open-scd/test/integration/__snapshots__/Setting.test.snap.js
- packages/open-scd/test/unit/Setting.test.ts
- packages/open-scd/test/unit/__snapshots__/Setting.test.snap.js
> feat: optional nsd upload button

- packages/open-scd/src/icons/icons.ts
- packages/plugins/src/editors/substation/bay-editor.ts
- packages/plugins/src/editors/substation/conducting-equipment-editor.ts
- packages/plugins/src/editors/substation/foundation.ts
- packages/plugins/src/editors/substation/line-editor.ts
- packages/plugins/src/editors/substation/powertransformer-editor.ts
- packages/plugins/src/editors/substation/process-editor.ts
- packages/plugins/src/editors/substation/substation-editor.ts
- packages/plugins/src/editors/substation/transformer-winding-editor.ts
- packages/plugins/src/editors/substation/voltage-level-editor.ts
- packages/plugins/test/unit/editors/substation/__snapshots__/bay-editor.test.snap.js
- packages/plugins/test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
- packages/plugins/test/unit/editors/substation/__snapshots__/line-editor.test.snap.js
- packages/plugins/test/unit/editors/substation/__snapshots__/powertransformer-editor.test.snap.js
- packages/plugins/test/unit/editors/substation/__snapshots__/process-editor.test.snap.js
- packages/plugins/test/unit/editors/substation/__snapshots__/substation-editor.test.snap.js
- packages/plugins/test/unit/editors/substation/__snapshots__/transformer-winding-editor.test.snap.js
- packages/plugins/test/unit/editors/substation/__snapshots__/voltage-level-editor.test.snap.js
> feat: add missing editor icons

- packages/core/package.json
When a PR is merged to main, the deployment action gets triggered. This action now fails because the doc script in core references to analyze, which doesn't exist in core anymore. 
In this PR the non existing script reference from doc has been removed.
> chore: fix failing deployment action

- packages/open-scd/src/translations/de.ts
- packages/open-scd/src/translations/en.ts
- packages/open-scd/test/integration/__snapshots__/open-scd.test.snap.js
help wanted with german translations for "plug-in" and "plug-ins"
closes #1429
> chore: update translations for plug-ins selector in drawer menu

- .github/workflows/build-and-deploy.yml
- packages/distribution/package.json
In this PR:
- Recovered build script for distribution package
- Updated build-and-deploy workflow
> ci: missing updates for build and deploy workflow to work again

- packages/openscd/src/addons/Layout.ts
> fix: re-enable input fields in custom plugins dialog

- packages/plugins/src/editors/subscription/foundation.ts
- packages/plugins/src/editors/subscription/later-binding/foundation.ts
- packages/plugins/test/testfiles/editors/ExtRefWithoutSrcLNClass.scd
- packages/plugins/test/unit/editors/subscription/foundation.test.ts
- packages/plugins/test/unit/editors/subscription/later-binding/foundation.test.ts
#1532  Use default value for ExtRef with missing srcLNClass
Take note there is a subtle difference how it is handled in `editors/subscription/foundation.ts` and `editors/subscription/later-binding/foundation.ts`:
- The first ignores the srcLNClass attribute completely for `LLN0` (coming from Control -> closest LN.lnClass)
- The second checks that the attribute in `ExtRef` is either missing or is `LLN0`
> bugfix(1532) Subscribing on minimal ExtRef definition

- packages/plugins/src/wizards/ln.ts
- packages/plugins/src/wizards/ln0.ts
- packages/plugins/test/unit/wizards/ln.test.ts
- packages/plugins/test/unit/wizards/ln0.test.ts
> fix: 1553 LN LN0 wizards read only attributes

- packages/openscd/src/foundation/nsdoc.ts
It seems better! I have not attempted to provide a regression test.
We don't seem to have linter rules (maybe we never did?) so I've avoided any specific formatting changes on this small PR.
> fix: store nsdocs correctly for descriptions (closes #1605)

- packages/openscd/src/foundation.ts
- packages/plugins/src/menu/VirtualTemplateIED.ts
- packages/plugins/test/unit/menu/__snapshots__/VirtualTemplateIED.test.snap.js
The bug is described here: https://github.com/openscd/open-scd/issues/1567
Description
When the user assigns multiple instances of a same LNType (even though instance numbers/prefixes are different) to a Function element, they are visualized just as normal with no problem like below;
Next, user creates a Virtual IED out of Functions which should turn out to LDs including those LNs within; (expected)
But at the end, it turns out to only last or first LN is included in the datamodel, and others are ignored.
Expected behaviour
Current problem:
> bugfix: Create virtual IED does not consider multiple instances of a LNType within a function

- .github/workflows/pr-preview.yml
The deploy PR preview job is no longer working because of a deprecated Ubuntu image (20.04). More info: https://github.com/actions/runner-images/issues/11101
To fix this, the ubuntu image is set to latest.
> fix: update deprecated ubuntu image in pr-preview workflow

- docs/core-api/oscd-api.md
- packages/core/api/api.ts
- packages/core/api/plugin-state-api.ts
- packages/core/foundation.ts
- packages/openscd/src/open-scd.ts
- packages/plugins/src/editors/IED.ts
- packages/plugins/test/integration/editors/IED.test.ts
Add an api to allow plugins to store state before being closed, so they can open the same context on their next activation. Use the state to preserve selected IED in the IED Plugin.
closes #1379
> feat: Add oscd api with plugin state
